title: Renan Lenhare
email: lenhare@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi. I’m Renan Lenhare, a developer based on Americana, São Paulo, Brazil. 
  Currently working at Secretaria de Saúde de Americana, and contributing to some open-source projects.
  Feel free to reach me on Mastodon and Bluesky!
baseurl: ""
url: "https://lenhare.dev"
github_username: lenhare
author:
  email: renan@lenhare.dev
  name: "Renan Lenhare"

# theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

favicon:
  source: devicon.png
  dir: .
feed:
  disable: true

header_pages:
  - index.md
  - about.md

style: dark
listen_for_clients_preferred_style: true

footer: 'Made with <a href="https://jekyllrb.com/">Jekyll</a> 🧪 and <a href="https://github.com/b2a3e8/jekyll-theme-console">Console Theme</a> 🎨'

google_analytics: UA-NNNNNNNN-N
